
class MemoryCardsGameResponse:
    CARDS_INITIALIZED,     GAME_IN_PROGRESS,     GUESS_ONE_ACCEPTED,     GUESS_TWO_ACCEPTED_MATCH,     GUESS_TWO_ACCEPTED_MATCH_END_OF_GAME_WIN,     GUESS_TWO_ACCEPTED_MISMATCH,     GUESS_TWO_ACCEPTED_MISMATCH_END_OF_GAME_LOSE,     GUESS_REJECTED_CARD_ALREADY_REVEALED,     GUESS_REJECTED_GAME_NOT_IN_PROGRESS = range(0, 9)
